### PR TITLE
[thread] Fix linker errors for OpenThread MTD build

### PR DESCRIPTION
**Pull request by Damian-Nordic**
- Add config variable CHIP_DEVICE_CONFIG_THREAD_FTD
  indicating if CHIP should use Full Thread Device features.
- On nrfconnect bind the variable to Kconfig variable
  CONFIG_OPENTHREAD_FTD.
- Fix ThreadStackManager build with FTD features disabled.

### CODE REVIEW

**Review by kkasperczyk-no — COMMENTED** [review]
Generally it looks good to me, but I have one doubt about approach of enabling FTD or not enabling FTD to consider. I guess that if we don't use FTD, then we have MTD, but wouldn't be cleaner in code to create two separate definitions and show it in the direct way? Looking forward on our further plans, we will have to define also settings for SED, so maybe we should think about some generic solution for such things.

**Comment by Damian-Nordic** [comment]
@kkasperczyk-no Are there any OpenThread MTD functions which are not part of FTD? If not, I think it's always better to have a single variable than two if there's no difference in terms of functionality. Having two variables causes confusion regarding which one to use to enable/disable a given functionality.

**Comment by kkasperczyk-no** [comment]
> @kkasperczyk-no Are there any OpenThread MTD functions which are not part of FTD? If not, I think it's always better to have a single variable than two if there's no difference in terms of functionality. Having two variables causes confusion regarding which one to use to enable/disable a given functionality.

I think that there are for MTD SED (e.g. disabling RX on idle to allow sleeping), but I'm not quite sure if it comes to the general MTD. I agree that two variables could cause confusion, but actually I meant something like setting CHIP_DEVICE_CONFIG_THREAD on one of three exclusive values of FTD, MTD and MTD_SED. Anyway that was just a suggestion, if you think that we may come back to talk about this, when we will have to introduce SED in CHIP - I'm ok with that.

**Comment by Damian-Nordic** [comment]
> I think that there are for MTD SED (e.g. disabling RX on idle to allow sleeping), but I'm not quite sure if it comes to the general MTD. I agree that two variables could cause confusion, but actually I meant something like setting CHIP_DEVICE_CONFIG_THREAD on one of three exclusive values of FTD, MTD and MTD_SED. Anyway that was just a suggestion, if you think that we may come back to talk about this, when we will have to introduce SED in CHIP - I'm ok with that.

Ah, ok. I think so far I haven't seen CHIP code referring to SED-only OpenThread functions, but if it becomes an issue we may rethink your proposal.

**Pull request closed without merging**
